server:
  port: 8085

spring:
  application:
    name: stock-service

  jackson:
    serialization:
      indent_output: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO

api:
  finnhub:
    key: cvfbc99r01qtu9s3scogcvfbc99r01qtu9s3scp0
      base-url: https://finnhub.io/api/v1

  alphavantage:
    key: 94JHN1RZIUTHER9S
