server:
  port: 8085

spring:
  application:
    name: stock-service

  jackson:
    serialization:
      indent_output: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    root: INFO
